from django.db import models

# Create your models here.
class quizzes(models.Model):

    quiz_name=models.CharField(max_length=50)
    topics=models.TextField()
    questions=models.IntegerField()
    time=models.IntegerField()
    ques1=models.CharField(max_length=50,null=type)
    ans1=models.CharField(max_length=50,null=type)
    op1_1=models.CharField(max_length=50,null=type)
    op1_2=models.CharField(max_length=50,null=type)
    op1_3=models.CharField(max_length=50,null=type)
    op1_4=models.CharField(max_length=50,null=type)
    ques2=models.CharField(max_length=50,null=type)
    ans2=models.CharField(max_length=50,null=type)
    op2_1=models.CharField(max_length=50,null=type)
    op2_2=models.CharField(max_length=50,null=type)
    op2_3=models.CharField(max_length=50,null=type)
    op2_4=models.CharField(max_length=50,null=type)
    ques3=models.CharField(max_length=50,null=type)
    ans3=models.CharField(max_length=50,null=type)
    op3_1=models.CharField(max_length=50,null=type)
    op3_2=models.CharField(max_length=50,null=type)
    op3_3=models.CharField(max_length=50,null=type)
    op3_4=models.CharField(max_length=50,null=type)
    ques4=models.CharField(max_length=50,null=type)
    ans4=models.CharField(max_length=50,null=type)
    op4_1=models.CharField(max_length=50,null=type)
    op4_2=models.CharField(max_length=50,null=type)
    op4_3=models.CharField(max_length=50,null=type)
    op4_4=models.CharField(max_length=50,null=type)
    ques5=models.CharField(max_length=50,null=type)
    ans5=models.CharField(max_length=50,null=type)
    op5_1=models.CharField(max_length=50,null=type)
    op5_2=models.CharField(max_length=50,null=type)
    op5_3=models.CharField(max_length=50,null=type)
    op5_4=models.CharField(max_length=50,null=type)
    