# Generated by Django 4.2.2 on 2023-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
                ('topics', models.TextField()),
                ('difficulty', models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy'), ('N', 'Not mentioned')], max_length=1)),
                ('questions', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
