# Generated by Django 4.2.2 on 2023-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizocrats', '0002_remove_quizzes_difficulty_quizzes_ans1_quizzes_ans2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='username',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
