# Generated by Django 4.2.2 on 2023-07-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizocrats', '0003_quizzes_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ans5',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op1_1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op1_2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op1_3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op1_4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op2_1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op2_2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op2_3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op2_4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op3_1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op3_2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op3_3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op3_4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op4_1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op4_2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op4_3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op4_4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op5_1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op5_2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op5_3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='op5_4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ques1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ques2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ques3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ques4',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='ques5',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='username',
        ),
        migrations.CreateModel(
            name='questionare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_opt', models.TextField()),
                ('opt1', models.TextField()),
                ('opt2', models.TextField()),
                ('opt3', models.TextField()),
                ('opt4', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizocrats.quizzes')),
            ],
        ),
    ]
