# Generated by Django 4.2.2 on 2023-07-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizocrats', '0006_result_delete_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
