# Generated by Django 4.2.2 on 2023-07-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizocrats', '0009_alter_quizzes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='user',
        ),
    ]
